[Bash Assignment] Implement 2 shell commands to parse a log file
abhinvv1/onboarding-assignment pull request #2
Opened 2024-07-23 13:42 UTC by abhinvv1

### Why?
This PR is to Implement 2 shell scripts to parse a log file.
1. `longest_time_to_execute.sh` script to identify and extract the HTTP request that took the longest time to process.
   - Uses `awk` to process the log file line by line.
   - Captures the HTTP method and path from 'Started' lines
   - Extracts the processing time from 'Completed' lines
   - Sorts the requests based on processing time
   - Outputs the time taken, method and path of the longest-running request
   - Usage: `./longest_time_to_execute tmp_more_than_50`
   - Sample Output:
   <img width="922" alt="Screenshot 2024-07-23 at 6 58 52 PM" src="https://github.com/user-attachments/assets/58032b20-bd01-4dea-a279-210a0daed035">
   
2. `count_endpoints.sh` script to extract and count unique endpoints
    - Extracts HTTP method and endpoint from log entries
    - Ignores query parameters to group similar endpoints
    - Counts occurrences of each unique endpoint and output them
    - The script consists of two main functions `map_endpoints` and `reduce_counts`
    - Usage: `./count_endpoints.sh`
    - Sample Output:
    <img width="1063" alt="Screenshot 2024-07-23 at 6 58 27 PM" src="https://github.com/user-attachments/assets/7c3b4f78-693b-4e03-b45b-87214bba82b0">

2024-08-02 13:35 UTC, yashdsaraf requested changes

2024-08-02 13:35 UTC, yashdsaraf commented on bash/count_endpoints.sh
> +sort -rn
3 constraints here
1. Single line command (this is pretty much done since you're artificially splitting the same line across multiple lines.
2. Try to keep the command <100 characters
3. Try to **not** use `awk` -- Since it undermines usage of other bash utilities due to its power.

2024-08-02 13:35 UTC, yashdsaraf commented on bash/longest_time_to_execute.sh
> +' "$1"
Same comment as above.

2024-08-08 21:13 UTC, yashdsaraf reviewed
Please refrain from using `awk` to do the heavy lifting. Command is single line and shortened now but the objective of clubbing multiple linux utilities together to achieve a singular goal is yet to be done.

2024-08-09 05:28 UTC, abhinvv1 commented
hey @yashdsaraf i've update the scripts to not use the `awk` and club different utilities to get the desired result, please take a look, thanks

2024-08-09 07:23 UTC, yashdsaraf approved these changes

2024-08-09 07:57 UTC, merged